### ISSUE TITLE
One Repo to Many Servers

### ISSUE THREAD

**Issue by maxexcloo** [kimdre/doco-cd#128]
I'm wondering if there's any way to use one repository to deploy to many servers - I understand that I can use `.doco-cd.yml` to specify which compose files to deploy (which is good!) but I can't actually specify which `.doco-cd.yml` file to use.

Maybe it would be good to have some way to specify that, so that I could use `.doco-cd.serverxyz.yml` format for example and write a new file for each server.

Curious if I've missed something or if you have any thoughts on this :)

**Comment by maxexcloo** [comment]
Maybe the webhook URL could have a variable for this - so I can just add one webhook per server (and this is easy to do programmatically using Terraform) and configure everything automagically 👍🏻

**Comment by kimdre** [comment]
I'm currently on vacation but I will check that when I'm back. 🙂
At least Github has a limit of 20 webhooks per repo afaik.

**Comment by maxexcloo** [comment]
20 is still pretty good!

Could also set the `.doco-cd.yml` file name via a Docker env per server also to overcome that limit.

Have a great break by the way 🏖️

**Comment by kimdre** [comment]
Since a YAML file can contain multiple YAML documents (seperated by `---`), I guess the easiest solution would be to just let the application read for multiple deploy configs in the normal `.doco-cd.yml` file.

So the file could then look like this:

```yaml
name: app1
working_dir: app1/
---
name: app2
working_dir: app2/
---
name: app3
working_dir: app3/
```

**Comment by maxexcloo** [comment]
But is there any way to conditionally deploy to just deploy to certain servers? Multiple apps in one file sound good though!

**Comment by kimdre** [comment]
Sorry, I didn't see you want to deploy to different servers. Yes that should be fairly easy to implement. However I'm unsure what would be the best solution.

The app could read the dynamic route of the webhook url and if the url has a additional suffix (`/v1/webhook/server1`) it could either check for the deploy config in a subdirectory with the same name or (as you mentioned) a file with a specifc prefix/suffix.

**Comment by kimdre** [comment]
I will implement it by using custom config files like `.doco-cd.serverxyz.yml` and webhook url `/v1/webhook/serverxyz`.

So if you send a webhook payload to a url like ` /v1/webhook/serverxyz`, the app wil automatically look for a related doco-cd config file (`.doco-cd.serverxyz.yml`). Besides this file, there is nothing else to configure or set up.

You can test it already by using the dev image: `ghcr.io/kimdre/doco-cd:dev`
Please let me know if this is what you wanted. :)

**Comment by maxexcloo** [comment]
That’s awesome! Exactly what I had in mind - will let you know how that goes when I test it :)

**Comment by kimdre** [comment]
> That’s awesome! Exactly what I had in mind - will let you know how that goes when I test it :)

Hi, have you been able to test it yet? :)

**Comment by maxexcloo** [comment]
Unfortunately not yet as my home server died this week and I've been trying to fix it :'(

**Comment by kimdre** [comment]
I will merge the changes and release them with v0.12.0
If you need any changes or find some bugs, please let me know in a new issue.
